import random
frase = 'Curso em Video Python'

#print(frase[9::3])
#print(frase[9:21])
#print(frase[15:])
#print(frase[:15])
#print(frase[15:21:2])
#print(len(frase))
#print(frase.count('o'))
#print(frase.count('o',0,13))
#print(frase.find('deo'))
#print(frase.find('android'))
#print('curso' in frase)
#print(frase.replace('python','android'))
#print(frase.upper())
#print(frase.lower())
#print(frase.capitalize())
#print(frase.title())
#print(len(frase.strip()))
#print(frase.rstrip())
#print(frase.lstrip())
#print(frase.split())
#print(frase.split())
#print('-'.join(frase))
#print(frase[3])
#print(frase[0:15:3])
#print(frase[::2])
#print("""um monte de frases estranhas
#em varias linhas diferentes
#para fazer isso coloco
#tres aspas no inicio e tres aspas no final""")
#print(frase.upper().count('o'))
#print(len(frase))
#print(frase.replace('em', 'de'))
#print(frase[0])
#frase[0] = 'j' isso da erro pois string é imutavel
#frase = frase.replace('python', 'android')
#print(frase)
#print('curso' in frase)
#print(frase.lower().find('video'))
#print(frase.find('jabuticaba'))
dividido = frase.split()
print(dividido[0])
#print(dividido[2][3])

