nome = str(input('digite seu nome completo: ')).strip()
print(f'ola,{nome}')
print(nome.upper(), 'é assim que ele fica em maiusculo')
print(nome.lower(), 'é assim que seu nome fica em minusculo')
n0 = nome.split()
print('seu nome captalizado fica',nome.title())
nome0 = nome.split()
nomesd = nome.replace(' ','')
print(f'seu nome tem ao todo {len(nomesd)} letras ')
print(f'seu primeiro nome tem {len(nome0[0])} caracteres')
